### ISSUE TITLE
rbenv_gem resource is not compatible with Chef 13

### ISSUE THREAD

**Issue by javmorin** [sous-chefs/ruby_rbenv#229] opened 2018-08-24 03:51 UTC
### Cookbook version
2.0.9

### Chef-client version
12.22.1

### Platform Details
Ubuntu 16.04

### Scenario:
Chef client reports a deprecation warning when rbenv_gem resounrce is used:
```
Deprecated features used!
  Property `ignore_failure` of resource `ruby_rbenv_gem` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/ruby_rbenv/resources/gem.rb:29:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
```

### Steps to Reproduce:
Build a cookbook that installs a gem using the rbenv_gem resource provided by ruby_rbenv

### Expected Result:
Cookbook runs without deprecation warnings

### Actual Result:
Cookbook runs, but deprecation warnings are generated, indicating Chef 13 will raise exceptions and fail.

**Comment by aried3r** [comment] 2018-08-28 13:36
Not a maintainer, but the README states that this cookbook requires Chef 13+, so this is expected. I'm not sure if there'll be any additional work for Chef 12.

**Comment by damacus** [comment] 2018-08-28 16:27
Closing as Chef-12 isn't a supported platform. That's our fault for not upping the version.

I've released `2.1.0`to make this clearer. 

Apologies for the understanding.

**Comment by javmorin** [comment] 2018-08-28 16:35
@aried3r @damacus I realize that Chef 12 is no longer supported. I had not been able to upgrade to Chef 13 because the current version of this cookbook was warning as above, and indicating it would fail with an exception if run on Chef 13. Does 2.1.0 fix this broken issue?

**Comment by damacus** [comment] 2018-08-29 08:11
These erorrs

**Comment by damacus** [comment] 2018-08-29 08:34
I'm going to close this down as I can't reproduce this locally using Chef 14. @javmorin you should be good to upgrade. 

This job in Travis installs ruby 2.4.1 can a few gems, and doesn't error like you suggested, so it might be a minor error with the Chef client you're using. 

https://travis-ci.org/sous-chefs/ruby_rbenv/jobs/421648868

**Comment by damacus** [comment] 2018-08-29 08:35
I'm also surprised it's only the one property that's throwing that error as we purposely mirror all of `gem`'s properties to pass them to gem! :)

**Closed as completed by damacus** 2018-08-29 08:35 UTC

**Comment by javmorin** [comment] 2018-08-29 15:42
@damacus Thanks for doing that sanity check. I will start rolling out to chef 13 with the current version of the cookbook and if something comes up, I will file a new bug. It is puzzling that they would make a big deal about a deprecation but in the end nothing happens. I had assumed that things would break as indicated and wasn't able to verify it myself (kitchen run was taking >60 minutes to run).

**Comment by damacus** [comment] 2018-08-29 17:49
Ouch, a 60 minute run. How many rubies are you installing?

**Comment by javmorin** [comment] 2018-08-29 17:52
This was running test kitchen for ruby_rbenv. I suspect I need to make some tweaks to my vagrant/virtualbox config to have it run better (my dev PC is in serious need of an upgrade as well)

**Comment by damacus** [comment] 2018-08-29 19:04
If you have any troubles don't hesitate to drop in on #sous-chefs in the chef community slack if you need anymore help! 👍
