### ISSUE TITLE
rbenv_ruby fails on osx due to no defined dep packages

### ISSUE THREAD

**Issue by bcg62** [sous-chefs/ruby_rbenv#205] opened 2018-01-25 19:08 UTC
```
  * ruby_rbenv_ruby[2.4.1] action install

    ================================================================================
    Error executing action `install` on resource 'ruby_rbenv_ruby[2.4.1]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    name is required

    Cookbook Trace:
    ---------------
    /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.PJ4QS38V/site-cookbooks/ruby_rbenv/resources/ruby.rb:89:in `install_ruby_dependencies'
    /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.PJ4QS38V/site-cookbooks/ruby_rbenv/resources/ruby.rb:42:in `block in class_from_file'
```

**Comment by xorima** [comment] 2019-05-13 18:28
Hi @bcg62 

Do you have the recipe to hand which caused this issue to make reproducing it easier?
Could you also confirm this is still an issue as #239 has been merged in

Thanks!

**Comment by damacus** [comment] 2021-05-24 08:50
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed as completed by damacus** 2021-05-24 08:50 UTC
Labels: Bug, Waiting on Contributor
