### ISSUE TITLE
Getting "undefined method `include_default_source' for Custom resource ruby_rbenv_gem from cookbook ruby_rbenv" on chef 13.0.118

### ISSUE THREAD

**Issue by potato20** [sous-chefs/ruby_rbenv#161] opened 2017-04-15 11:16 UTC
### Cookbook version
1.2.0

### Chef-client version
chef-client 13.0.118 in the vm. locally using chefdk 1.3.40, ran the cookbook using kitchen.

### Platform Details
ubuntu 16.04

### Scenario:
Just trying to install a rbenv gem

### Steps to Reproduce:

Attributes:
```
node.default['rbenv']['rubies'] = [ "2.4.0" ]
node.default['rbenv']['global'] = "2.4.0"
```

Recipe:

```
ruby_version = '2.4.0'

include_recipe 'ruby_build'
include_recipe 'ruby_rbenv::system'

%w(bundler rake).each do |gem_name|
  rbenv_gem gem_name do
    rbenv_version ruby_version
  end
end
```

### Expected Result:
Everything works great, bundler and rake gems install on ruby 2.4.0, system-wide.

### Actual Result:
system rbenv and ruby 2.4.0 works fine but the `rbenv_gem` lwrp fails:

```
Recipe: ror::default
         * [2.4.0::bundler] (system) action install
           
           ================================================================================
           Error executing action `install` on resource '[2.4.0::bundler] (system)'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `include_default_source' for Custom resource ruby_rbenv_gem from cookbook ruby_rbenv
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/ror/recipes/default.rb
           
            19:   rbenv_gem gem_name do
            20:     rbenv_version ruby_version
            21:   end
            22: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/ror/recipes/default.rb:19:in `block in from_file'
           
           ruby_rbenv_gem("bundler") do
             provider Chef::Provider::Package::RbenvRubygems
             action [:install]
             default_guard_interpreter :default
             declared_type :rbenv_gem
             cookbook_name "ror"
             recipe_name "default"
             rbenv_version "2.4.0"
             package_name "bundler"
             gem_binary "export RBENV_ROOT=\"/usr/local/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"2.4.0\" && $RBENV_ROOT/shims/gem"
           end
           
           System Info:
           ------------
           chef_version=13.0.118
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1725;start=10:47:16;
           executable=/opt/chef/bin/chef-client
```

**Comment by potato20** [comment] 2017-04-15 11:57
Seems to work fine on chef client version 12.19.36. Possibly a 13.x bug regarding `include_default_source`

**Comment by mattcl** [comment] 2017-04-16 02:22
That's not the only problem. I worked around it by modifying the provider, but then got hit by this (from the chef 13 changelog)

> DSL-based custom resources and providers no longer get module constants¶
Up until now, creating a mycook/resources/thing.rb would create a Chef::Resources::MycookThing name to access the resource class object. This const is no longer created for resources and providers. You can access resource classes through the resolver API like:
Chef::Resource.resource_for_node(:mycook_thing, node)

There's something that tries to reference Chef::Resource::RubyRbenvRehash, so I have to fix that too, now that I know what the problem is.

**Comment by mattcl** [comment] 2017-04-16 04:26
https://github.com/mattcl/ruby_rbenv/commit/cae7d9a0ef29565eb992d7938e7ead90e69a0754 Seems to do the trick, but I haven't updated the tests.

**Comment by aried3r** [comment] 2017-06-03 15:45
@mattcl, nice! Care to make a PR so we can get a discussion started and possibly get this merged? :)

**Comment by damacus** [comment] 2017-06-10 14:33
Hey everyone! 

Thanks for the discussion. If anyone wants to help maintain this cookbook going forward please drop us a line in the sous-chefs room on the chef community slack. 

If you don't like slack just reply to this ticket and I should see it! 

Thanks!
Dan

**Closed** 2017-06-23 16:03 UTC
